### PR TITLE
style consistency

### PR DESCRIPTION
**Pull request by ksunden**
- Style consistency in tomorrow night default theme
- Checkbox source svg

### CODE REVIEW

**Comment by untzag** [comment]
@ksunden the checkboxes don't show up at all on my machine

**Comment by ksunden** [comment]
pngs were ignored due to git ignore problems, added now...

As for the "spreadsheet" aesthetic, I don't fully disagree, but think its better than the mix of system theme and our themes that resulted before, and was going for "easy, I want a border that indicates interaction"

Happy to change it, but not sure that we have anything concrete in mind for desired look and feel.

**Comment by untzag** [comment]
I think a bit of vertical breathing room would be nice.

For context, could you post here a screenshot of old PyCMDS?

**Comment by ksunden** [comment]
image


I tend to agree, I think, though can't be _too_ much, as need I remind you that one of the biggest complaints I've gotten about apps that use this is the scrolling ... 

Perhaps there are other answers to that particular complaint, though

**Pull request merged**
